openapi: 3.1.0
info:
  title: Notification Service API
  description: API for handling notifications in the e-commerce system
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8084
    description: Local development server

paths:
  /api/notifications:
    get:
      summary: Get all notifications
      description: Retrieve a list of notifications
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
    post:
      summary: Create new notification
      description: Send a new notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
      responses:
        '201':
          description: Notification created successfully

components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
        message:
          type: string
        type:
          type: string
          enum: [EMAIL, SMS, PUSH]
        status:
          type: string
          enum: [SENT, PENDING, FAILED]
        createdAt:
          type: string
          format: date-time

    NotificationRequest:
      type: object
      required:
        - userId
        - message
        - type
      properties:
        userId:
          type: string
        message:
          type: string
        type:
          type: string
          enum: [EMAIL, SMS, PUSH]