services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ../services/user
    container_name: user-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - DATABASE_DOCKER_URL=postgres://postgres:postgres@postgres:5432/ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    depends_on:
      - postgres
    # command: npx knex migrate:latest --knexfile knexfile.js && npm run start

volumes:
  pgdata:
